name: CloudFront Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.17

      - name: Setup dotenv
        run: echo "${{ secrets.ENV }}" | base64 --decode > .env

      - name: Install requirements
        run: npm ci

      - name: Build static files
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Deploy files
        run: aws s3 cp . s3://${{secrets.BUCKET_NAME}} --recursive

      - name: Invalidate cache on CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths '/*'
